version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    image: talkcorner/api
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - IS_PRODUCTION=yes
    depends_on:
      migrations:
        condition: service_completed_successfully
      nats:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://server:${SERVER_PORT}/api/v1/healthcheck/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  broadcaster:
    build:
      context: ./
      dockerfile: docker/broadcaster/Dockerfile
    image: talkcorner/broadcaster
    restart: always
    env_file:
      - .env
    environment:
      - IS_PRODUCTION=yes
    depends_on:
      nats:
        condition: service_started

  migrations:
    build:
      context: ./
      dockerfile: docker/migrations/Dockerfile
    image: talkcorner/migrations
    env_file:
      - .env
    environment:
      - IS_PRODUCTION=yes
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/:z
    restart: always
    env_file:
      - .env
    expose:
      - "${PG_PORT}"
    environment:
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats
    volumes:
      - ./nats/data:/etc/nats
    restart: always
    env_file:
      - .env
    expose:
      - "${NATS_CLIENT_PORT}"
      - "${NATS_HTTP_PORT}"
      - "${NATS_ROUTING_PORT}"
    command: ["-js", "--user", "${NATS_USER}", "--pass", "${NATS_PASSWORD}"]