"""added creator_id for topic and topic_message

Revision ID: 6ffd44c77713
Revises: 432e03d49357
Create Date: 2023-06-12 20:00:42.552998

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ffd44c77713"
down_revision = "432e03d49357"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topic_messages", sa.Column("creator_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "topic_messages_creator_id_fkey",
        "topic_messages",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("topics", sa.Column("creator_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "topics_creator_id_fkey",
        "topics",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("topics_creator_id_fkey", "topics", type_="foreignkey")
    op.drop_column("topics", "creator_id")
    op.drop_constraint(
        "topic_messages_creator_id_fkey", "topic_messages", type_="foreignkey"
    )
    op.drop_column("topic_messages", "creator_id")
    # ### end Alembic commands ###
