"""added creator_id for subforum

Revision ID: a873c9884afb
Revises: 8e9c789a74bd
Create Date: 2023-06-11 14:25:01.321415

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a873c9884afb"
down_revision = "8e9c789a74bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subforums", sa.Column("creator_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "subforums_creator_id_fkey", "subforums", "users", ["creator_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subforums_creator_id_fkey", "subforums", type_="foreignkey")
    op.drop_column("subforums", "creator_id")
    # ### end Alembic commands ###
