"""added unique constraint for parent and child forums

Revision ID: 8e9c789a74bd
Revises: 0ad0d75755e5
Create Date: 2023-06-11 13:55:52.155017

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e9c789a74bd"
down_revision = "0ad0d75755e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "subforums_parent_child_forums",
        "subforums",
        ["parent_forum_id", "child_forum_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subforums_parent_child_forums", "subforums", type_="unique")
    # ### end Alembic commands ###
