"""added ondelete cascade for tables

Revision ID: 432e03d49357
Revises: a873c9884afb
Create Date: 2023-06-12 19:52:07.314284

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "432e03d49357"
down_revision = "a873c9884afb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("forums_creator_id_fkey", "forums", type_="foreignkey")
    op.create_foreign_key(
        "forums_creator_id_fkey",
        "forums",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("subforums_child_forum_id_fkey", "subforums", type_="foreignkey")
    op.drop_constraint("subforums_creator_id_fkey", "subforums", type_="foreignkey")
    op.drop_constraint(
        "subforums_parent_forum_id_fkey", "subforums", type_="foreignkey"
    )
    op.create_foreign_key(
        "subforums_child_forum_id_fkey",
        "subforums",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "subforums_creator_id_fkey",
        "subforums",
        "forums",
        ["parent_forum_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "subforums_parent_forum_id_fkey",
        "subforums",
        "forums",
        ["child_forum_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "topic_messages_topic_id_fkey", "topic_messages", type_="foreignkey"
    )
    op.create_foreign_key(
        "topic_messages_topic_id_fkey",
        "topic_messages",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("topics_forum_id_fkey", "topics", type_="foreignkey")
    op.create_foreign_key(
        "topics_forum_id_fkey",
        "topics",
        "forums",
        ["forum_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("topics_forum_id_fkey", "topics", type_="foreignkey")
    op.create_foreign_key(
        "topics_forum_id_fkey", "topics", "forums", ["forum_id"], ["id"]
    )
    op.drop_constraint(
        "topic_messages_topic_id_fkey", "topic_messages", type_="foreignkey"
    )
    op.create_foreign_key(
        "topic_messages_topic_id_fkey", "topic_messages", "topics", ["topic_id"], ["id"]
    )
    op.drop_constraint(
        "subforums_parent_forum_id_fkey", "subforums", type_="foreignkey"
    )
    op.drop_constraint("subforums_creator_id_fkey", "subforums", type_="foreignkey")
    op.drop_constraint("subforums_child_forum_id_fkey", "subforums", type_="foreignkey")
    op.create_foreign_key(
        "subforums_parent_forum_id_fkey",
        "subforums",
        "forums",
        ["parent_forum_id"],
        ["id"],
    )
    op.create_foreign_key(
        "subforums_creator_id_fkey", "subforums", "users", ["creator_id"], ["id"]
    )
    op.create_foreign_key(
        "subforums_child_forum_id_fkey",
        "subforums",
        "forums",
        ["child_forum_id"],
        ["id"],
    )
    op.drop_constraint("forums_creator_id_fkey", "forums", type_="foreignkey")
    op.create_foreign_key(
        "forums_creator_id_fkey", "forums", "users", ["creator_id"], ["id"]
    )
    # ### end Alembic commands ###
