name: Python lint and test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: python3 -m pip install poetry && poetry install
      - name: Run ruff
        run: poetry run ruff check .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: python3 -m pip install poetry && poetry install
      - name: Run tests
        run: poetry run pytest